spring.application.name=Spring06_FileUpload

# port 번호 설정
server.port=9000
# context path 
server.servlet.context-path=/Spring06

# 업로드 파일의 최대크기
spring.servlet.multipart.max-file-size=50MB

# 업로드 요청의 최대크기(파일의 크기 + 폼 전송되는 문자열)
spring.servlet.multipart.max-request-size=60MB

# file save location
file.location=C:/playground/upload